name: Action Practice

on:
  push:
  schedule:
    - cron: '0 22 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -U requests
      - name: Run
        env: 
          EMAIL: ${{ secrets.EMAIL}}
          PASSWORD: ${{ secrets.PASSWORD}}
          BASE_URL: ${{ secrets.BASE_URL}}
          SCKEY: ${{ secrets.SCKEY}}
        run: python3 main.py
